name: board_game_lovers
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  http: ^1.2.1
  html: ^0.15.0
  flutter_html: ^3.0.0-beta.2
  bgg_api: ^0.8.0
  flutter:
    sdk: flutter
  go_router: ^14.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
