name: board_game_lovers
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  http: ^1.2.1
  html: ^0.15.0
  flutter_html: ^3.0.0-beta.2
  bgg_api: ^0.8.0
  flutter:
    sdk: flutter
  go_router: ^14.0.1
  font_awesome_flutter: ^10.1.0
  cached_network_image: ^3.0.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  cloud_firestore: ^4.17.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_logo.png
    
